# Generated by Django 3.2.25 on 2024-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodelname',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
