# Generated by Django 5.0.4 on 2024-04-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerec_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
