# Generated by Django 5.0.4 on 2024-05-09 11:37

import Ecommerec_Website.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerec_Website', '0005_carditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), Ecommerec_Website.models.validate_image_size]),
        ),
    ]
