version: '3'
services:
  myapp:
    ports:
      - 8888:8888
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/root
    command: bash -c "jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root"
